# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SPTuts' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SPTuts

  pod 'AFNetworking', '~> 3.0'
  pod 'FBSDKCoreKit', '~> 4.9'

end
